# Use official Python slim image for AMD64
FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /app/django_proj

# Copy Django project files
COPY ./django_proj ./
COPY ./requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose Django port
EXPOSE 8001

# Run Django server
CMD ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8001", "django_proj.wsgi:application"]
