services:
  fastapi:
    image: fastapi-app-amd64  # Use local image
    command: uvicorn myapp.fastapi:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  django:
    image: django-app-amd64  # Use local image
    command: gunicorn --workers 3 --bind 0.0.0.0:8001 django_proj.wsgi:application
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
